import * as Lucide from "lucide-react";
import { cn } from "@/shared/utils/cn";

const ICONS = {
  account_circle: Lucide.CircleUserRound,
  account_tree: Lucide.GitFork,
  add: Lucide.Plus,
  air: Lucide.Wind,
  api: Lucide.Braces,
  apps: Lucide.Grid3X3,
  arrow_back: Lucide.ArrowLeft,
  arrow_downward: Lucide.ArrowDown,
  arrow_forward: Lucide.ArrowRight,
  arrow_upward: Lucide.ArrowUp,
  attach_file: Lucide.Paperclip,
  auto_awesome: Lucide.Sparkles,
  bar_chart: Lucide.ChartColumn,
  block: Lucide.Ban,
  blur_on: Lucide.CircleDotDashed,
  bolt: Lucide.Zap,
  brush: Lucide.Paintbrush,
  business: Lucide.Building2,
  cancel: Lucide.CircleX,
  cast: Lucide.Cast,
  chat: Lucide.MessageCircle,
  check: Lucide.Check,
  check_circle: Lucide.CircleCheck,
  checklist: Lucide.ListChecks,
  chevron_left: Lucide.ChevronLeft,
  chevron_right: Lucide.ChevronRight,
  close: Lucide.X,
  cloud: Lucide.Cloud,
  cloud_download: Lucide.CloudDownload,
  cloud_off: Lucide.CloudOff,
  cloud_queue: Lucide.Cloud,
  cloud_sync: Lucide.CloudCog,
  cloud_upload: Lucide.CloudUpload,
  code: Lucide.Code2,
  computer: Lucide.Monitor,
  content_copy: Lucide.Copy,
  cookie: Lucide.Cookie,
  dashboard: Lucide.LayoutDashboard,
  dark_mode: Lucide.Moon,
  data_array: Lucide.Brackets,
  data_object: Lucide.Braces,
  data_usage: Lucide.Gauge,
  delete: Lucide.Trash2,
  developer_board: Lucide.CircuitBoard,
  devices: Lucide.TabletSmartphone,
  diamond: Lucide.Gem,
  dns: Lucide.Network,
  download: Lucide.Download,
  edit: Lucide.Pencil,
  edit_note: Lucide.FilePenLine,
  error: Lucide.CircleAlert,
  expand_more: Lucide.ChevronDown,
  extension: Lucide.Puzzle,
  face: Lucide.Smile,
  file_upload: Lucide.FileUp,
  folder_open: Lucide.FolderOpen,
  grid_view: Lucide.LayoutGrid,
  group: Lucide.Users,
  group_work: Lucide.Network,
  help: Lucide.CircleHelp,
  history: Lucide.History,
  hourglass_top: Lucide.Hourglass,
  hub: Lucide.Network,
  info: Lucide.Info,
  input: Lucide.LogIn,
  key: Lucide.KeyRound,
  keyboard_arrow_down: Lucide.ChevronDown,
  keyboard_arrow_up: Lucide.ChevronUp,
  language: Lucide.Languages,
  lan: Lucide.EthernetPort,
  layers: Lucide.Layers,
  light_mode: Lucide.Sun,
  link: Lucide.Link,
  local_fire_department: Lucide.Flame,
  lock: Lucide.Lock,
  lock_open: Lucide.LockOpen,
  logout: Lucide.LogOut,
  menu: Lucide.Menu,
  manage_search: Lucide.SearchCheck,
  memory: Lucide.MemoryStick,
  menu_book: Lucide.BookOpen,
  mic: Lucide.Mic,
  monitor: Lucide.Monitor,
  monitoring: Lucide.ChartSpline,
  movie: Lucide.Film,
  music_note: Lucide.Music,
  open_in_new: Lucide.ExternalLink,
  output: Lucide.LogOut,
  pause_circle: Lucide.CirclePause,
  perm_media: Lucide.Images,
  play_arrow: Lucide.Play,
  play_circle: Lucide.CirclePlay,
  power_off: Lucide.PowerOff,
  power_settings_new: Lucide.Power,
  progress_activity: Lucide.LoaderCircle,
  public: Lucide.Globe2,
  psychology: Lucide.Brain,
  psychology_alt: Lucide.BrainCircuit,
  qr_code_scanner: Lucide.ScanQrCode,
  record_voice_over: Lucide.AudioLines,
  refresh: Lucide.RefreshCw,
  restart_alt: Lucide.RotateCcw,
  restore: Lucide.RotateCcw,
  rocket_launch: Lucide.Rocket,
  route: Lucide.Route,
  router: Lucide.Router,
  save: Lucide.Save,
  saved_search: Lucide.SearchCheck,
  scatter_plot: Lucide.ScatterChart,
  schedule: Lucide.Clock,
  science: Lucide.FlaskConical,
  search: Lucide.Search,
  search_off: Lucide.SearchX,
  security: Lucide.Shield,
  send: Lucide.Send,
  settings: Lucide.Settings,
  shield: Lucide.Shield,
  shield_with_heart: Lucide.ShieldPlus,
  shield_lock: Lucide.ShieldCheck,
  smart_toy: Lucide.Bot,
  spatial_audio: Lucide.AudioLines,
  speaker: Lucide.Volume2,
  speed: Lucide.Gauge,
  star: Lucide.Star,
  stop: Lucide.Square,
  stop_circle: Lucide.CircleStop,
  terminal: Lucide.Terminal,
  translate: Lucide.Languages,
  travel_explore: Lucide.Globe2,
  toggle_off: Lucide.ToggleLeft,
  toggle_on: Lucide.ToggleRight,
  upload: Lucide.Upload,
  verified_user: Lucide.BadgeCheck,
  vpn_lock: Lucide.ShieldCheck,
  vpn_key: Lucide.KeyRound,
  warning: Lucide.TriangleAlert,
  water_drop: Lucide.Droplet,
  wifi: Lucide.Wifi,
  wifi_off: Lucide.WifiOff,
  wifi_tethering: Lucide.RadioTower,
};

export default function Icon({ name, className, title, ...props }) {
  const LucideIcon = ICONS[name] || Lucide.CircleHelp;

  return (
    <LucideIcon
      aria-hidden={title ? undefined : true}
      className={cn("inline-block shrink-0", className)}
      focusable="false"
      height="1em"
      width="1em"
      {...props}
    >
      {title ? <title>{title}</title> : null}
    </LucideIcon>
  );
}
